name: "master"

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: antyung88
          password: ${{ secrets.GH_TOKEN }}
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            ghcr.io/antyung88/docker-tor-socks5/docker-tor-socks5
          push: ${{ github.ref == 'refs/heads/main' }}
